name: Release Egosystem proxys binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64,windows/amd64,linux/darwin
        goos: [linux,windows,darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/"
          binary_name: "proxyctl"
          ldflags: "-s -w"
          # extra_files: LICENSE README.md
  releases-matrix-arm:
      name: Release Go Binary
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # build and publish in parallel: linux/arm
          goos: [linux]
          goarch: [arm]
      steps:
        - uses: actions/checkout@v2
        - uses: wangyoucao577/go-release-action@v1.16
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            project_path: "./cmd/"
            binary_name: "proxyctl"
            ldflags: "-s -w"
            # extra_files: LICENSE README.md